default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch('RAILS_MAX_THREADS', 5) %>
  username: <%= ENV.fetch('DB_USER', 'postgres') %>
  password: <%= ENV.fetch('DB_PASS', 'sekret') %>
  host: <%= ENV.fetch('DB_HOST', 'localhost') %>

development:
  primary: &primary_development
    <<: *default
    database: flashmemo_development
  queue:
    <<: *primary_development
    database: flashmemo_development_queue
    migrations_paths: db/queue_migrate

test:
  primary: &primary_test
    <<: *default
    database: flashmemo_test
  queue:
    <<: *primary_test
    database: flashmemo_test_queue
    migrations_paths: db/queue_migrate

production:
  primary: &primary_production
    <<: *default
    database: flashmemo_production
  queue:
    <<: *primary_production
    database: flashmemo_production_queue
    migrations_paths: db/queue_migrate
