development:
  decay_tree_health:
    class: DecayTreeHealthJob
    queue: background
    schedule: every week
  progress_trees_lifecycle:
    class: ProgressTreesLifecycleJob
    queue: background
    schedule: every day
  send_review_email:
    class: SendReviewEmailJob
    queue: background
    schedule: every day
