# frozen_string_literal: true

source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '3.3.4'

gem 'bcrypt', '~> 3.1'
gem 'bootsnap', require: false
gem 'image_processing', '~> 1.2'
gem 'jbuilder', '~> 2.13.0'
gem 'jwt', '~> 3.1'
gem 'pg', '~> 1.5.9'
gem 'puma', '~> 6.6'
gem 'rails', '~> 8.0.0'
gem 'rmagick', '~> 6.0.1'
gem 'sqlite3', '~> 2.5'
gem 'tzinfo-data', platforms: %i[ windows jruby ]
gem 'kamal', require: false
gem 'thruster', require: false

# Use the database-backed adapters for Rails.cache, Active Job, and Action Cable
gem 'solid_cache'
gem 'solid_queue'
gem 'solid_cable'

group :development, :test do
  gem 'debug', platforms: %i[ mri windows ], require: 'debug/prelude'
  gem 'dotenv', '~> 3.1'
  gem 'factory_bot_rails', '~> 6.2'
  gem 'faker', '~> 3.2'
  gem 'rspec-rails', '~> 7.1.0'
  gem 'rubocop-rails', '~> 2.32', require: false
  gem 'rubocop-rspec', '~> 3.3.0', require: false
  gem 'rubocop-rails-omakase', require: false
  gem 'shoulda-matchers', '~> 5.1'
end

group :development do
  gem 'brakeman', require: false
end
