# frozen_string_literal: true

source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '3.2.0'

gem 'bcrypt', '~> 3.1'
gem 'bootsnap', require: false
gem 'image_processing', '~> 1.2'
gem 'jbuilder', '~> 2.11'
gem 'jwt', '~> 2.7'
gem 'pg', '~> 1.1'
gem 'puma', '~> 5.6'
gem 'rails', '~> 7.0.4'
gem 'rmagick', '~> 5.3'
gem 'sqlite3', '~> 1.4'
gem 'tzinfo-data', platforms: %i[mingw mswin x64_mingw jruby]

group :development, :test do
  gem 'debug', platforms: %i[mri mingw x64_mingw]
  gem 'dotenv', '~> 3.1', '>= 3.1.2'
  gem 'factory_bot_rails', '~> 6.2'
  gem 'faker', '~> 3.2'
  gem 'rspec-rails', '~> 6.0'
  gem 'rubocop-rails', '~> 2.19', require: false
  gem 'rubocop-rspec', '~> 2.22', require: false
  gem 'shoulda-matchers', '~> 5.1'
  gem 'whenever', '~> 1.0', require: false
end

group :development do
end
